CREATE file format RPE_APOLLO.NAMELY.PARQUET_FILE_FORMAT
type = PARQUET
BINARY_AS_TEXT = TRUE
USE_LOGICAL_TYPE = TRUE
TRIM_SPACE = TRUE
REPLACE_INVALID_CHARACTERS = TRUE;


-- Creating Stage for S3 Namely profile data in snowflake
CREATE OR REPLACE STAGE S3_NAMELY_PROFILE
STORAGE_INTEGRATION = AWS_S3_INTEGRATION
URL = 's3://riverdale-analytics/namely_custom/profiles/data/'
FILE_FORMAT = RPE_APOLLO.NAMELY.PARQUET_FILE_FORMAT;


-- Pipe for profile_incremental_load 
create or replace pipe RPE_APOLLO.NAMELY.PROFILE_INCREMENTAL_LOAD auto_ingest=true as COPY INTO RPE_APOLLO.NAMELY.INCREMENTAL_UPDATE_PROFILE
    FROM @RPE_APOLLO.NAMELY.S3_NAMELY_PROFILE
    file_format =  (FORMAT_NAME = RPE_APOLLO.NAMELY.PARQUET_FILE_FORMAT)
    match_by_column_name = case_insensitive;


-- CREATE DYNAMIC TABLE
CREATE OR REPLACE DYNAMIC TABLE PROFILE_TO_INSERT
TARGET_LAG = '240 minute'
WAREHOUSE = COMPUTE_WH
AS
SELECT *
FROM INCREMENTAL_UPDATE_PROFILE
WHERE INCREMENTAL_UPDATE_PROFILE._fivetran_batch = (SELECT MAX(INCREMENTAL_UPDATE_PROFILE._fivetran_batch) FROM INCREMENTAL_UPDATE_PROFILE);

SELECT * FROM INCREMENTAL_UPDATE_PROFILE;