CREATE file format RPE_APOLLO.NAMELY.PARQUET_FILE_FORMAT
type = PARQUET
BINARY_AS_TEXT = TRUE
USE_LOGICAL_TYPE = TRUE
TRIM_SPACE = TRUE
REPLACE_INVALID_CHARACTERS = TRUE;


-- Creating Stage for S3 Namely profile data in snowflake
CREATE OR REPLACE STAGE S3_NAMELY_PROFILE
STORAGE_INTEGRATION = AWS_S3_INTEGRATION
URL = 's3://riverdale-analytics/namely_custom/profiles/data/'
FILE_FORMAT = RPE_APOLLO.NAMELY.PARQUET_FILE_FORMAT;


-- Pipe for profile_incremental_load 
create or replace pipe RPE_APOLLO.NAMELY.PROFILE_INCREMENTAL_LOAD auto_ingest=true as COPY INTO RPE_APOLLO.NAMELY.INCREMENTAL_UPDATE_PROFILE
    FROM @RPE_APOLLO.NAMELY.S3_NAMELY_PROFILE
    file_format =  (FORMAT_NAME = RPE_APOLLO.NAMELY.PARQUET_FILE_FORMAT)
    match_by_column_name = case_insensitive;


-- CREATE DYNAMIC TABLE
CREATE OR REPLACE DYNAMIC TABLE RPE_APOLLO.NAMELY.PROFILE_TO_INSERT
TARGET_LAG = '60 minute'
WAREHOUSE = COMPUTE_WH
AS
WITH RankedUpdates AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _fivetran_index DESC) AS rn
    FROM INCREMENTAL_UPDATE_PROFILE
    WHERE _fivetran_batch = (SELECT MAX(_fivetran_batch) FROM INCREMENTAL_UPDATE_PROFILE)
)
SELECT *
FROM RankedUpdates
WHERE rn = 1;



WITH RankedUpdates AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _fivetran_index DESC) AS rn
    FROM INCREMENTAL_UPDATE_PROFILE
    WHERE _fivetran_batch = (SELECT MAX(_fivetran_batch) FROM INCREMENTAL_UPDATE_PROFILE)
)
SELECT *
FROM RankedUpdates
WHERE rn = 1;



-- column updates
--pipeline canada

ALTER TABLE rpe_apollo.namely.profile
ADD COLUMN PIPELINE_CARD_NUMBER_N VARCHAR(16777216);

UPDATE rpe_apollo.namely.profile
SET PIPELINE_CARD_NUMBER_N = CAST(PIPELINE_CARD_NUMBER AS VARCHAR);


ALTER TABLE rpe_apollo.namely.profile
DROP COLUMN PIPELINE_CARD_NUMBER;


ALTER TABLE rpe_apollo.namely.profile
RENAME COLUMN PIPELINE_CARD_NUMBER_N TO PIPELINE_CARD_NUMBER;

--INP

ALTER TABLE rpe_apollo.namely.profile
ADD COLUMN IPN_CARD_N VARCHAR(16777216);

UPDATE rpe_apollo.namely.profile
SET IPN_CARD_N = CAST(IPN_CARD AS VARCHAR);


ALTER TABLE rpe_apollo.namely.profile
DROP COLUMN IPN_CARD;


ALTER TABLE rpe_apollo.namely.profile
RENAME COLUMN IPN_CARD_N TO IPN_CARD;

--Shopify password
ALTER TABLE rpe_apollo.namely.profile
ADD COLUMN SHOPIFY_PASSWORD_N VARCHAR(16777216);

UPDATE rpe_apollo.namely.profile
SET SHOPIFY_PASSWORD_N = CAST(SHOPIFY_PASSWORD_N AS VARCHAR);


ALTER TABLE rpe_apollo.namely.profile
DROP COLUMN SHOPIFY_PASSWORD;


ALTER TABLE rpe_apollo.namely.profile
RENAME COLUMN SHOPIFY_PASSWORD_N TO SHOPIFY_PASSWORD;


--petro canada

ALTER TABLE rpe_apollo.namely.profile
ADD COLUMN PETRO_CAN_CARD_NUMBER_N VARCHAR(16777216);

UPDATE rpe_apollo.namely.profile
SET PETRO_CAN_CARD_NUMBER_N = CAST(PETRO_CAN_CARD_NUMBER AS VARCHAR);


ALTER TABLE rpe_apollo.namely.profile
DROP COLUMN PETRO_CAN_CARD_NUMBER;


ALTER TABLE rpe_apollo.namely.profile
RENAME COLUMN PETRO_CAN_CARD_NUMBER_N TO PETRO_CAN_CARD_NUMBER;


--ELMIRA_TRUCK_SERVICE

ALTER TABLE rpe_apollo.namely.profile
ADD COLUMN ELMIRA_TRUCK_SERVICE_N VARCHAR(16777216);

UPDATE rpe_apollo.namely.profile
SET ELMIRA_TRUCK_SERVICE_N = CAST(ELMIRA_TRUCK_SERVICE AS VARCHAR);


ALTER TABLE rpe_apollo.namely.profile
DROP COLUMN ELMIRA_TRUCK_SERVICE;


ALTER TABLE rpe_apollo.namely.profile
RENAME COLUMN ELMIRA_TRUCK_SERVICE_N TO ELMIRA_TRUCK_SERVICE;


--RIVERDALE_PROVIDED_PHONE_NUMBER

ALTER TABLE rpe_apollo.namely.profile
ADD COLUMN RIVERDALE_PROVIDED_PHONE_NUMBER_N VARCHAR(16777216);

UPDATE rpe_apollo.namely.profile
SET RIVERDALE_PROVIDED_PHONE_NUMBER_N = CAST(RIVERDALE_PROVIDED_PHONE_NUMBER AS VARCHAR);


ALTER TABLE rpe_apollo.namely.profile
DROP COLUMN RIVERDALE_PROVIDED_PHONE_NUMBER;


ALTER TABLE rpe_apollo.namely.profile
RENAME COLUMN RIVERDALE_PROVIDED_PHONE_NUMBER_N TO RIVERDALE_PROVIDED_PHONE_NUMBER;


COPY INTO RPE_APOLLO.NAMELY.INCREMENTAL_UPDATE_PROFILE
    FROM @RPE_APOLLO.NAMELY.S3_NAMELY_PROFILE/2024-06-21T17-16-28Z_6180f42b-1353-45cd-bb2f-558d2a799417.parquet
    file_format =  (FORMAT_NAME = RPE_APOLLO.NAMELY.PARQUET_FILE_FORMAT)
    match_by_column_name = case_insensitive;


desc table incremental_update_profile;


SELECT _fivetran_batch, count(_fivetran_batch) as count_batch FROM INCREMENTAL_UPDATE_PROFILE group by _fivetran_batch order by _fivetran_batch;

SELECT * FROM PROFILE;

select * from incremental_update_profile;

SELECT * FROM INCREMENTAL_UPDATE_PROFILE where _fivetran_batch = (SELECT MIN(_fivetran_batch) FROM INCREMENTAL_UPDATE_PROFILE);

select * from PROFILE_TO_INSERT;


CALL UPDATEPROFILE();


CREATE TASK RPE_APOLLO.NAMELY.UPDATE_PROFILE
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '60 minutes'
    AS CALL UPDATEPROFILE();

ALTER TASK RPE_APOLLO.NAMELY.UPDATE_PROFILE RESUME;