create or replace pipe RPE_APOLLO.NAMELY_FIVETRAN.PROFILE_GROUP_INCREMENTAL_LOAD auto_ingest=true as COPY INTO RPE_APOLLO.NAMELY_FIVETRAN.INCREMENTAL_UPDATE_PROFILE_GROUP
    FROM @RPE_APOLLO.NAMELY_FIVETRAN.S3_NAMELY_PROFILE_GROUP
    file_format =  (FORMAT_NAME = RPE_APOLLO.NAMELY_FIVETRAN.NAMELY_PARQUET_FORMAT)
    match_by_column_name = case_insensitive;

